---
title: "R Notebook"
output: html_notebook
---

```{r}
source("Hogares_data_preparation.R")
```

```{r}
library(rpart)
library(caret)
library(rpart.plot)
library(stringr)
```

```{r}
#Function to wraps long split labels over multiple lines.
#Used to improve visualitazion of decision trees using the
#rpart.plot function
#Source: https://stackoverflow.com/questions/22618751/rpart-plot-text-shorter
split_fun <- function(x, labs, digits, varlen, faclen)
{
    # replace commas with spaces (needed for strwrap)
    labs <- gsub(",", " ", labs)
    for(i in 1:length(labs)) {
        # split labs[i] into multiple lines
        labs[i] <- paste(strwrap(labs[i], width=25), collapse="\n")
    }
    labs
}

#prp(tree, split.fun=split.fun)
```






```{r}
#6th ITERATION
#Select target and predictor variables
target_field <- 62
#predictor_fields <- c(9,13:15,17:24)#with work_class
predictor_fields <- c(13:15,17,18,21:24)#without work_class
model_fields <- c(target_field,predictor_fields)
#metadata2$english_labels[predictor_fields]
#to make the code more concise we simplify the formula and select the 
#predictors subseting the imput dataset
tree5_formula <- as.formula(paste0(metadata2$english_labels[target_field],"~."))

```

```{r}

```



```{r}
#Create test and training sets

set.seed(1234)
training_index <- createDataPartition(hogares.clean$food_safety_category,p=0.7,list = F)
UPsampled_data <- caret::upSample(hogares.clean[training_index,],hogares.clean[training_index,target_field])
UPsampled_data <- UPsampled_data[-which(names(UPsampled_data) == "Class")]
table(hogares.clean[training_index,target_field])
table(UPsampled_data$food_safety_category)
```


```{r}
tree_cp <- 0.01 #complexity parameter
sink("Reports/tree_performance.txt",append = T)#,type = "message")
abr_time_old <- ""
for (tree_cp in c(0.02,0.01,0.005)) {


    #We log the parameters and performance of different models in a text file
    writeLines("----#----#----#----#----#----#----#----#----#----#----#----#----")
    #We log the time
    abr_time <- Sys.time() %>% str_replace_all(":","-")%>% str_replace_all(" ","_")
    while(abr_time==abr_time_old){
      Sys.sleep(0.3)#we delay the loop execution a little so we don't produce
                  #more than a plot per second (wich will overwrite due to duplicated names)
      abr_time <- Sys.time() %>% str_replace_all(":","-")%>% str_replace_all(" ","_")
    }
    writeLines(as.character(Sys.time()))
    
    #we log the model cp
    writeLines(paste0("cp_parameter: ",tree_cp))
    writeLines("\n")
    
    #we log the output levels
    output_levels <- paste0(levels(hogares.clean[[target_field]]),collapse = ", ")
    writeLines(paste0("output_levels: ",output_levels))
    #we log the plot name and predictor variables
    plot_name <- paste0("Reports/tree_plot_",abr_time,".png")
    writeLines(paste0("plot_name: ",str_replace(plot_name,"Reports/","")))
    pred_var_name <- paste0(names(hogares.clean[predictor_fields]),collapse = ", ")
    pred_var_nr<- paste0(predictor_fields,collapse = ", ")
    writeLines(paste0("predictor_variables_nr: ",pred_var_nr))
    writeLines(paste0("predictor_variables_name: ",pred_var_name))
    writeLines("\n")
    
    #We create the decision tree model using rpart function
    tree5_model <- rpart(tree5_formula, method="class", data=UPsampled_data[model_fields],control = rpart.control(cp = tree_cp))
    
    #We log Variable importance
    writeLines("Variable Importance:")
    variable_importance <- ""
    capture.output(model_sum <- summary(tree5_model))
    if(!is.null(model_sum$variable.importance)){
    variable_importance <- cbind(names(model_sum$variable.importance), as.character(round(model_sum$variable.importance,digits = 5)))
    }
    print(variable_importance)
    writeLines("\n")
    writeLines("-----COMPLEXITY PARAMETER TABLE-----")
    printcp(tree5_model)
    writeLines("\n")
    
    #Confusion matrix test set
    writeLines("-----TEST SET - CONFUSION MATRIX-----")
    pred<-predict(tree5_model,hogares.clean[-training_index,model_fields],type = "class")
    tree5_conf_matrix<-confusionMatrix(pred, hogares.clean[-training_index,target_field])
    print(tree5_conf_matrix)
    #Confusion matrix training set
    writeLines("\n")
    writeLines("-----TRAINING SET - CONFUSION MATRIX-----")
    pred<-predict(tree5_model,hogares.clean[training_index,model_fields],type = "class")
    tree5_conf_matrix<-confusionMatrix(pred, hogares.clean[training_index,target_field])
    print(tree5_conf_matrix)
    writeLines("\n\n\n")
    png(filename=plot_name, 
      units="in", 
      width=5, 
      height=4, 
      pointsize=12, 
      res=720)
    rpart.plot(tree5_model, extra=104, fallen.leaves = T, type=4,split.fun=split_fun,
               faclen = 30,box.palette = list("Greens", "Grays", "Reds"))
    dev.off()
    abr_time_old <- abr_time
    

}
sink()

```


