---
title: "R Notebook"
output: html_notebook
---

```{r}
source("Hogares_data_preparation.R")
library(parallel)
```


```{r}

#Select target and predictor variables
target_field <- 62
predictor_fields <- c(13:15,17,18,21:24)#without work_class, home_type2 only
predictor_fields <- c(13:15,17,18,21:42,50,51,56,57,78)#all w/o social plans
model_fields <- c(target_field,predictor_fields)
#metadata2$english_labels[predictor_fields]
#to make the code more concise we simplify the formula and select the 
#predictors subseting the imput dataset
model_formula <- as.formula(paste0(metadata2$english_labels[target_field],"~."))

```
```{r}
#We decide fi we want to merge the unsafety and some_unsafety classes
will_merge <- T
#We decide if we want to oversample to deal with the unbalanced data
will_oversample <-T

merge_suffix <- "_wO_merge"
plot_colors <- list("Greens", "Grays", "Reds")
if(will_merge){

    #We merge the some_unsafety and safety categories in an attempt
    #to improve the prediction accuracy
    hogares.clean <- merge_unsafety_some(hogares.clean)
    merge_suffix <- "_wmerg"
    plot_colors <- list("Greens", "Reds")
}


#Create test and training sets

set.seed(1234)
training_index <- createDataPartition(hogares.clean$food_safety_category,p=0.7,list = F)

oversample_suffix <- "_wO_oversamp"
training_data <- hogares.clean[training_index,]
if (will_oversample){
  training_data <- upSample(hogares.clean[training_index,],hogares.clean[training_index,                                                                   target_field])
  training_data <- training_data[-which(names(training_data) == "Class")]
  oversample_suffix <- "_wosamp"
}

table(training_data$food_safety_category)
file_suffix <- paste0(merge_suffix,oversample_suffix)

```


```{r}
abr_time <- Sys.time() %>% str_replace_all(":","-")%>% str_replace_all(" ","_")
report_filename <- paste0("Reports/SVM_",abr_time,"_",file_suffix,".txt")
sink(report_filename,append = T)



#We log the parameters and performance of different models in a text file
writeLines("----#----#----#----#----#----#----#----#----#----#----#----#----")
#We log the time


writeLines(as.character(Sys.time()))
writeLines("Source Filename: Hogares_model_14_SVM_Caret.Rmd")

    
#we log the output levels
output_levels <- paste0(levels(hogares.clean[[target_field]]),collapse = ", ")
writeLines(paste0("output_levels: ",output_levels))

#we log the plot name and predictor variables
pred_var_name <- paste0(names(hogares.clean[predictor_fields]),collapse = ", ")
pred_var_nr<- paste0(predictor_fields,collapse = ", ")
writeLines(paste0("predictor_variables_nr: ",pred_var_nr))
writeLines(paste0("predictor_variables_name: ",pred_var_name))
writeLines("\n")

#WE CREATE THE MODEL
home_model_12 <- train(model_formula,training_data[model_fields],
                       method = "svmLinearWeights",na.action=na.exclude)

    

    
    #Confusion matrix test set
    writeLines("-----TEST SET - CONFUSION MATRIX-----")
    pred<-predict(home_model_12,hogares.clean[-training_index,model_fields])
    tree5_conf_matrix<-confusionMatrix(pred, hogares.clean[-training_index,target_field])
    print(tree5_conf_matrix)

    #Confusion matrix training set
    writeLines("\n")
    
    writeLines("-----TRAINING SET - CONFUSION MATRIX-----")
    pred<-predict(home_model_12,newdata=hogares.clean[training_index,model_fields])
    tree5_conf_matrix<-confusionMatrix(pred, hogares.clean[training_index,target_field])
    print(tree5_conf_matrix)
    writeLines("\n\n\n")
    

    abr_time_old <- abr_time
    
    
   
    
    writeLines("-----MODEL DETAILS-----")
    print(home_model_12)
    writeLines("\n")
    
    writeLines("-----VARIABLE IMPORTANCE-----")
    rm(variable_importance)
    variable_importance <- varImp(home_model_12)
    var_imp_order <- order(variable_importance$importance[1],decreasing = T)
    var_imp_print <- variable_importance$importance[var_imp_order,]
    #if 2 classes
    #if 3 classes
    if(will_merge){
      write.table(format(var_imp_print[1],digits = 5),report_filename,sep='\t\t',row.names=T,append =T)}
    if(!will_merge){write.table(format(var_imp_print,digits = 5),
                report_filename, sep='\t\t',row.names=T,append = T)}
    




sink()

```


