---
title: "R Notebook"
output: html_notebook
---

```{r}
library(foreign)
```
```{r}
#hogares (homes)
hogares.filename <- "Base EDSA hogares 2010.Difusión (V.BETA).sav"
#hogares2 <- haven::read_sav(hogares.filename)
hogares <- read.spss(hogares.filename)
hogares.attr<-attributes(hogares)
hogares.df <- read.spss(hogares.filename,to.data.frame = T)
#file.create("test.txt")
#lapply(str(hogares), write, "test.txt", append=TRUE, ncolumns=1000)
temp <- hogares.df["P35"]
View(temp)
```
```{r}
class(hogares.attr)
#test1 NOT working
#write(hogares.attr$label.table,file = "hogares_table.txt")
writeLines(names(hogares),"fields.csv")
#test2 https://stackoverflow.com/questions/27594541/export-a-list-into-a-csv-or-txt-file-in-r
hogares.labels <- hogares.attr$label.table
lapply(hogares.labels, function(x) write.table( data.frame(x), 'comments.csv'  , append= T, sep=',' ))
#test3
lapply(hogares.labels, function(x) write(paste(names(x),x,sep = ";"), file='test3.csv'  , append= T))
#test4
lines <- function(l) lapply(l, function(x) writeLines(paste(names(x),x,sep = ";"),'test4.csv'))
lapply(hogares.attr$label.table, names)
#test5 (Not optimal, but has all the information, not used)
sink("Descriptions.txt",append = T)
hogares.label
sink("MoreData.txt",append = T)
lapply()

sink()
hogares.df[4]
```

```{r}
writeLines(names(hogares),"fields.csv")
lapply(hogares.attr$label.table, function(x) write.table( data.frame(x), 'comments.csv'  , append= T, sep=',' ))
lapply(hogares.attr$variable.labels, function(x) write.table( data.frame(x), 'var_labels.csv'  , append= T, sep=',' ))
```

```{r}
non.factor.fields <- c(1,2,3,4,5,6,53,54,55)
names(hogares.df)[non.factor.fields]
sapply(hogares.df[-non.factor.fields],table)
```
```{r}
table(hogares.df$NBI_Baño)
table(hogares.df$NBI_Capacidad_subsistencia)
```

