---
title: "R Notebook"
output: html_notebook
---

```{r}
source("Hogares_data_preparation.R")
library(mlr)
```


```{r}
#Multinomial Naive Bayes Model

#Select target and predictor variables
target_field <- 62
#predictor_fields <- c(9,13:15,17:24)#with work_class
predictor_fields <- c(13:15,17,18,21:24)#without work_class
predictor_fields <- c(13:15,17,18,21:24,30,34,50)#without work_class
model_fields <- c(target_field,predictor_fields)
#metadata2$english_labels[predictor_fields]
#to make the code more concise we simplify the formula and select the 
#predictors subseting the imput dataset
model_formula <- as.formula(paste0(metadata2$english_labels[target_field],"~."))

```
```{r}
#We decide fi we want to merge the unsafety and some_unsafety classes
will_merge <- T
#We decide if we want to oversample to deal with the unbalanced data
will_oversample <-T

merge_suffix <- "_wO_merge"
plot_colors <- list("Greens", "Grays", "Reds")
if(will_merge){

    #We merge the some_unsafety and safety categories in an attempt
    #to improve the prediction accuracy
    hogares.clean <- merge_unsafety_some(hogares.clean)
    merge_suffix <- "_w_merge"
    plot_colors <- list("Greens", "Reds")
}


#Create test and training sets

set.seed(1234)
training_index <- createDataPartition(hogares.clean$food_safety_category,p=0.7,list = F)

oversample_suffix <- "_wO_oversamp"
training_data <- hogares.clean[training_index,]
if (will_oversample){
  training_data <- upSample(hogares.clean[training_index,],hogares.clean[training_index,                                                                   target_field])
  training_data <- training_data[-which(names(training_data) == "Class")]
  oversample_suffix <- "_w_oversamp"
}

table(training_data$food_safety_category)
file_suffix <- paste0(merge_suffix,oversample_suffix)

```


```{r}
report_filename <- paste0("Reports/model_performance",file_suffix,".txt")
sink(report_filename,append = F)



    #We log the parameters and performance of different models in a text file
    writeLines("----#----#----#----#----#----#----#----#----#----#----#----#----")
    #We log the time
    abr_time <- Sys.time() %>% str_replace_all(":","-")%>% str_replace_all(" ","_")

    writeLines(as.character(Sys.time()))
    

    
    #we log the output levels
    output_levels <- paste0(levels(hogares.clean[[target_field]]),collapse = ", ")
    writeLines(paste0("output_levels: ",output_levels))
    
    #we log the plot name and predictor variables
    plot_name <- paste0("Reports/tree_plot_",abr_time,".png")
    writeLines(paste0("plot_name: ",str_replace(plot_name,"Reports/","")))
    pred_var <- paste0(names(hogares.clean[predictor_fields]),collapse = ", ")
    writeLines(paste0("predictor_varialbeles: ",pred_var))
    writeLines("\n")
    
    #WE CREATE THE MODEL with mlr package
    #Source:https://www.r-bloggers.com/understanding-naive-bayes-classifier-using-r/
    
    #Create a classification task for learning on the Dataset 
    #and specify the target   feature
    training_data$food_safety_category
    target_name <- names(hogares.clean)[target_field]
    mlr_task = makeClassifTask(data = training_data[model_fields], target=target_name)
     
    #Initialize the Naive Bayes classifier
    selected_model = makeLearner("classif.naiveBayes")
     
    #Train the model
    NB_mlr = mlr::train(selected_model, mlr_task)
     
    #Read the model learned  
    NB_mlr$learner.model
    
    
    
    #rminer::Importance(NB_mlr,UPsampled_data[model_fields])

    
    #Confusion matrix test set
    writeLines("-----TEST SET - CONFUSION MATRIX-----")
    pred<-predict(NB_mlr,newdata=hogares.clean[-training_index,model_fields],type="class")
    tree5_conf_matrix<-confusionMatrix(pred, hogares.clean[-training_index,target_field])
    print(tree5_conf_matrix)
    #Confusion matrix training set
    writeLines("\n")
    
    writeLines("-----TRAINING SET - CONFUSION MATRIX-----")
    pred<-predict(NB_mlr,newdata=hogares.clean[training_index,model_fields],type = "class")
    tree5_conf_matrix<-confusionMatrix(pred, hogares.clean[training_index,target_field])
    print(tree5_conf_matrix)
    writeLines("\n\n\n")
    

    abr_time_old <- abr_time
    
    
    # weight_sum <- apply(NB_mlr$tables[[1]],2,FUN=sum)
    # table <- NB_mlr$tables[[1]]
    # attributes(table) <- NULL
    # dim <- attributes(table)[[2]]
    # attributes(table)[[2]]
    # attributes(table)[[3]]
  
    # var_weight <- base::as.data.frame(NB_mlr$tables[[1]])
    # var_weight <- mapply("/",NB_mlr$tables[[1]],var_weight)
    
    var_weight <- melt(NB_mlr$tables[[1]])
    var_weight$Var <- names(NB_mlr$tables[1])
    var_weight <- var_weight[c(4,2,1,3)]
    names(var_weight) <- c("var","value_var","value_food_safety","prob")
    var_sum <- data.frame(level=levels(var_weight[[2]]),
                    sum=as.vector(tapply(var_weight[[4]],var_weight[[2]],sum)))
    names(var_sum)[1] <- names(var_weight[2])
    var_weight <- merge(var_weight, var_sum)
    var_weight$weight <- var_weight$prob/var_weight$sum
    
    for (i in c(2:length(NB_mlr$tables))){
          temp_var_weight <- melt(NB_mlr$tables[[i]])
          temp_var_weight$Var <- names(NB_mlr$tables[i])
          temp_var_weight <- temp_var_weight[c(4,2,1,3)]
          names(temp_var_weight) <- c("var","value_var","value_food_safety","prob")
          temp_var_weight$value_var <- factor(temp_var_weight$value_var)
          temp_var_sum <- data.frame(level=levels(temp_var_weight[[2]]),        sum=as.vector(tapply(temp_var_weight[[4]],temp_var_weight[[2]],sum)))
          names(temp_var_sum)[1] <- names(temp_var_weight[2])
          temp_var_weight <- merge(temp_var_weight, temp_var_sum)
          temp_var_weight$weight <- temp_var_weight$prob/temp_var_weight$sum
          var_weight <- rbind.data.frame(var_weight,temp_var_weight)
          
          
      
    }
    
    var_weight <- var_weight[order(var_weight$weight,decreasing =T ),]
    
    #"-----VARIABLE WEIGHT -----")
    write.csv(var_weight,paste0("Reports/var_weight",file_suffix,".csv"))
    
    writeLines("-----MODEL DETAILS-----")
    print(NB_mlr)
    writeLines("\n")



sink()

```


