---
title: "R Notebook"
output: html_notebook
---


```{r}
#install.packages("ggplot2")
library(foreign)
library(ggplot2)
library(plyr)
```
```{r}
#hogares (homes)
#Reading the .sav file (SPSS)
hogares.filename <- "Base EDSA hogares 2010.Difusión (V.BETA).sav"
hogares <- read.spss(hogares.filename)
hogares.attr<-attributes(hogares)
hogares.df <- read.spss(hogares.filename,to.data.frame = T)
#str(hogares.df)
#Writing data into a CSV
#write.csv(hogares.df,file="homes_data.csv")
#Removing 29 observations with missing values (5682 to 5653)
hogares.clean <- hogares.df[!is.na(hogares.df$PON_HOG),]
str(hogares.clean)
#LOST FIELD ATTRIBUTES DOING THIS

```
```{r}
binary.fields<-sapply(hogares.df,nlevels)==2
names(hogares.df)[binary.fields]
paste(unname(which(binary.fields)),collapse=", ")
poverty.binary <- c( 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 45, 47, 48, 58, 59, 60, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79)
names(poverty.binary) <-  names(hogares.df)[poverty.binary]
poverty.binary
```
```{r}

poverty.binary.df <- hogares.clean[poverty.binary]
pov.bin.meta <- as.data.frame(hogares.attr[c(2,3)])[poverty.binary,]
pov.bin.meta <- cbind.data.frame(field_nr=poverty.binary,pov.bin.meta)
poverty.binary.df <- as.data.frame(sapply(poverty.binary.df,as.factor))
#test about changing levels


levels(poverty.binary.df[[26]])
#this rename the current levels
levels(poverty.binary.df[[26]]) <- c("not_deficitary","deficitary")
#this change the order of the extisting levels
poverty.binary.df[[26]]<-factor(poverty.binary.df[[26]],levels = c("deficitary","not_deficitary"))
table(poverty.binary.df[[26]])
```

```{r}
#this was a sanity check to be performed befor and after the name changing
sapply(poverty.binary.df[swap.levels],table)
level.byn <- as.data.frame(sapply(poverty.binary.df,levels))
View(as.data.frame(sapply(poverty.binary.df,table)))
```
```{r}
#testing melt
mydata <- mtcars[, c(1,3,4,5,6,7)]
head(mydata)
cormat <- round(cor(mydata),2)
head(cormat)
melted_cormat <- melt(cormat)
head(melted_cormat)
```

